# This workflow will install Python dependencies, then perform static linting analysis.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Run linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Analyze src code with linter
      run: |
        pylint -rn -sn --recursive=y ./src --rcfile=./src/.pylintrc
    - name: Analyze tests code with linter
      if: success() || failure()
      run: |
        pylint -rn -sn --recursive=y ./tests --rcfile=./tests/.pylintrc
    - name: Analyze benchmarks code with linter
      if: success() || failure()
      run: |
        pylint -rn -sn --recursive=y ./benchmarks --rcfile=./tests/.pylintrc