# This workflow runs pre-commit hooks on pull requests to enforce coding style.
# To ensure correct configuration, please refer to:
#   https://lincc-ppt.readthedocs.io/en/latest/practices/ci_precommit.html
name: Run pre-commit hooks

on:
  pull_request:
    branches: [ main ]

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  pre-commit-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux, Python 3.11
            os: ubuntu-22.04
            python-version: "3.11"
            toxenv: py311-test
            gfortran-version: 11
          - name: macOS, Python 3.10, coverage
            os: macOS-11
            python-version: "3.10"
    env: 
      SKIP: "check-lincc-frameworks-template-version,no-commit-to-branch,check-added-large-files,pytest-check,sphinx-build"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        # sudo apt-get update
        python -m pip install --upgrade pip
        pip install .[dev]
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()